package com.example.composemultitheming.core.theme.color_schemes

import androidx.compose.ui.graphics.Color

val red_md_theme_light_primary = Color(0xFFA03F27)
val red_md_theme_light_onPrimary = Color(0xFFFFFFFF)
val red_md_theme_light_primaryContainer = Color(0xFFFFDAD2)
val red_md_theme_light_onPrimaryContainer = Color(0xFF3C0700)
val red_md_theme_light_secondary = Color(0xFF755B00)
val red_md_theme_light_onSecondary = Color(0xFFFFFFFF)
val red_md_theme_light_secondaryContainer = Color(0xFFFFE08F)
val red_md_theme_light_onSecondaryContainer = Color(0xFF241A00)
val red_md_theme_light_tertiary = Color(0xFF6D5D2E)
val red_md_theme_light_onTertiary = Color(0xFFFFFFFF)
val red_md_theme_light_tertiaryContainer = Color(0xFFF7E1A6)
val red_md_theme_light_onTertiaryContainer = Color(0xFF241A00)
val red_md_theme_light_error = Color(0xFFBA1A1A)
val red_md_theme_light_errorContainer = Color(0xFFFFDAD6)
val red_md_theme_light_onError = Color(0xFFFFFFFF)
val red_md_theme_light_onErrorContainer = Color(0xFF410002)
val red_md_theme_light_background = Color(0xFFFFFBFF)
val red_md_theme_light_onBackground = Color(0xFF201A19)
val red_md_theme_light_surface = Color(0xFFFFFBFF)
val red_md_theme_light_onSurface = Color(0xFF201A19)
val red_md_theme_light_surfaceVariant = Color(0xFFF5DDD8)
val red_md_theme_light_onSurfaceVariant = Color(0xFF534340)
val red_md_theme_light_outline = Color(0xFF85736F)
val red_md_theme_light_inverseOnSurface = Color(0xFFFBEEEB)
val red_md_theme_light_inverseSurface = Color(0xFF362F2D)
val red_md_theme_light_inversePrimary = Color(0xFFFFB4A2)
val red_md_theme_light_shadow = Color(0xFF000000)
val red_md_theme_light_surfaceTint = Color(0xFFA03F27)
val red_md_theme_light_outlineVariant = Color(0xFFD8C2BD)
val red_md_theme_light_scrim = Color(0xFF000000)

val red_md_theme_dark_primary = Color(0xFFFFB4A2)
val red_md_theme_dark_onPrimary = Color(0xFF611200)
val red_md_theme_dark_primaryContainer = Color(0xFF812812)
val red_md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD2)
val red_md_theme_dark_secondary = Color(0xFFEBC248)
val red_md_theme_dark_onSecondary = Color(0xFF3D2E00)
val red_md_theme_dark_secondaryContainer = Color(0xFF584400)
val red_md_theme_dark_onSecondaryContainer = Color(0xFFFFE08F)
val red_md_theme_dark_tertiary = Color(0xFFDAC58C)
val red_md_theme_dark_onTertiary = Color(0xFF3C2F04)
val red_md_theme_dark_tertiaryContainer = Color(0xFF544519)
val red_md_theme_dark_onTertiaryContainer = Color(0xFFF7E1A6)
val red_md_theme_dark_error = Color(0xFFFFB4AB)
val red_md_theme_dark_errorContainer = Color(0xFF93000A)
val red_md_theme_dark_onError = Color(0xFF690005)
val red_md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val red_md_theme_dark_background = Color(0xFF201A19)
val red_md_theme_dark_onBackground = Color(0xFFEDE0DD)
val red_md_theme_dark_surface = Color(0xFF201A19)
val red_md_theme_dark_onSurface = Color(0xFFEDE0DD)
val red_md_theme_dark_surfaceVariant = Color(0xFF534340)
val red_md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BD)
val red_md_theme_dark_outline = Color(0xFFA08C88)
val red_md_theme_dark_inverseOnSurface = Color(0xFF201A19)
val red_md_theme_dark_inverseSurface = Color(0xFFEDE0DD)
val red_md_theme_dark_inversePrimary = Color(0xFFA03F27)
val red_md_theme_dark_shadow = Color(0xFF000000)
val red_md_theme_dark_surfaceTint = Color(0xFFFFB4A2)
val red_md_theme_dark_outlineVariant = Color(0xFF534340)
val red_md_theme_dark_scrim = Color(0xFF000000)

val red_seed = Color(0xFFA03F27)
